# Generated by Django 4.2.7 on 2024-03-11 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_page', '0013_alter_statictemplate_options_and_more'),
        ('userprofile', '0003_alter_profile_options_profile_is_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_page.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.profile')),
            ],
            options={
                'verbose_name': 'Авторский тег',
                'verbose_name_plural': 'Авторские теги',
                'unique_together': {('user', 'tag')},
            },
        ),
    ]
