# Generated by Django 4.2.7 on 2024-03-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_page', '0013_alter_statictemplate_options_and_more'),
        ('userprofile', '0004_usertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(related_name='user_profiles', to='post_page.tag', verbose_name='Теги'),
        ),
    ]
