# Generated by Django 4.2.7 on 2024-01-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_mobile', models.ImageField(upload_to='banners/')),
                ('image_tablet', models.ImageField(upload_to='banners/')),
                ('image_desktop', models.ImageField(upload_to='banners/')),
                ('url', models.URLField()),
            ],
        ),
    ]
