# Generated by Django 4.2.7 on 2024-02-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0004_alter_banner_options_alter_banner_image_desktop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='show_on_main',
            field=models.BooleanField(default=True, verbose_name='Показывать на главной странице'),
        ),
    ]
