# Generated by Django 4.2.7 on 2023-12-26 08:36

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Image')),
            ],
        ),
    ]
