# Generated by Django 4.2.7 on 2023-12-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_page', '0002_delete_myfiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyFiles',
        ),
    ]
