# Generated by Django 4.2.7 on 2023-12-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_page', '0002_postcategory_alter_tag_options_remove_post_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='Category', to='post_page.category'),
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
