# Generated by Django 4.2.7 on 2024-01-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_page', '0004_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='card_display',
            field=models.CharField(choices=[('default', 'Фото + Заголовок'), ('fullscreen', 'Фото на всю ширину с оверфлоу + Заголовок поверх фото')], default='default', max_length=20, verbose_name='Вид карточки'),
        ),
    ]
