# Generated by Django 4.2.7 on 2024-02-09 13:01

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post_page', '0006_alter_post_card_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
