# Generated by Django 4.2.7 on 2024-02-21 11:10

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post_page', '0007_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=django_summernote.fields.SummernoteTextField(max_length=150, verbose_name='Краткое описание'),
        ),
    ]
