# Generated by Django 4.2.7 on 2024-02-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_page', '0008_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_card',
            field=models.ImageField(default=None, upload_to='images/%Y/%m-%d', verbose_name='Фото для карточки категорий'),
        ),
    ]
