# Generated by Django 4.2.7 on 2024-02-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_page', '0009_post_img_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page',
            field=models.IntegerField(default=None, verbose_name='Номер страницы в журнале'),
        ),
    ]
