# Generated by Django 4.2.7 on 2024-03-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_usersubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corporatesubscription',
            options={'verbose_name': 'Подписка Юр-лиц', 'verbose_name_plural': 'Подписка Юр-лиц'},
        ),
    ]
