"""
Django settings for ukniga_NEW project.

Generated by 'django-admin startproject' using Django 3.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$$r@&)-ge4idep0d-l=$6w&96tn8s@hnp1&bbg97e3^-2=ztew'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'filebrowser',
    'jet.dashboard',
    'jet',
    'captcha',
    'subscriptions',
    'django_summernote',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'post_page.apps.PostPageConfig',
    'slider.apps.SliderConfig',
    'django_ckeditor_5',
    'ckeditor',
    'ckeditor_uploader',
    'userprofile.apps.UserprofileConfig',
    'tinymce',
    'django_q',
]

Q_CLUSTER = {
    'name': 'DjangoORM',
    'workers': 4,
    'timeout': 90,
    'retry': 120,
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default',  # использует базу данных Django для хранения задач
}

SUMMERNOTE_CONFIG = {
    # Using SummernoteWidget - iframe mode, default
    'iframe': True,

    # Or, you can set it to `False` to use SummernoteInplaceWidget by default - no iframe mode
    # In this case, you have to load Bootstrap/jQuery sources and dependencies manually.
    # Use this when you're already using Bootstrap/jQuery based themes.
    'iframe': False,

    # You can put custom Summernote settings
    'summernote': {
        # As an example, using Summernote Air-mode
        'airMode': False,

        # Change editor size
        'width': '100%',
        'height': '480',

        # Use proper language setting automatically (default)
        'lang': None,

        # Toolbar customization
        # https://summernote.org/deep-dive/#custom-toolbar-popover
        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['fontname', ['fontname']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'codeview', 'help']],
        ],
        
        'codemirror': {
            'mode': 'htmlmixed',
            'lineNumbers': 'true',
            # You have to include theme file in 'css' or 'css_for_inplace' before using it.
            'theme': 'monokai',
        },
    },
    # You can also add custom css/js for SummernoteInplaceWidget.
    # !!! Be sure to put {{ form.media }} in template before initiate summernote.
    'css_for_inplace': (
    ),
    'js_for_inplace': (
    ),

    # Codemirror as codeview
    # If any codemirror settings are defined, it will include codemirror files automatically.
    'css': (
        '//cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/theme/monokai.min.css',
    ),

    # Lazy initialization
    # If you want to initialize summernote at the bottom of page, set this as True
    # and call `initSummernote()` on your page.
    'lazy': True,
}

CKEDITOR_UPLOAD_PATH = 'images/' # Папка для загруженных изображений
CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js'  # Подключите jQuery или другой файл-менеджер
CKEDITOR_IMAGE_BACKEND = "pillow"  # Используйте Pillow для обработки изображений
CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": "Custom",
        "height": 800,
        "width": 1200,
        "filebrowserBrowseUrl": '/admin/filebrowser/browse/',
        "filebrowserUploadUrl": '/admin/filebrowser/upload/',
        "filebrowserImageBrowseUrl": '/admin/filebrowser/browse/?type=Image',
        "filebrowserImageUploadUrl": '/admin/filebrowser/upload/?type=Image',
        'uiColor': '#9ccde5',
        'extraPlugins': 'filebrowser',  # Включение плагина файлового браузера
    },
    'awesome_ckeditor': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', 'Link'],
            ['Image', 'FileBrowser'],
        ],
        'filebrowserBrowseUrl': '/admin/filebrowser/browse/',
        'filebrowserUploadUrl': '/admin/filebrowser/upload/',
        'filebrowserImageBrowseUrl': '/admin/filebrowser/browse/?type=Image',
        'filebrowserImageUploadUrl': '/admin/filebrowser/upload/?type=Image',
    },
}

# customColorPalette = [
#         {
#             'color': 'hsl(4, 90%, 58%)',
#             'label': 'Red'
#         },
#         {
#             'color': 'hsl(340, 82%, 52%)',
#             'label': 'Pink'
#         },
#         {
#             'color': 'hsl(291, 64%, 42%)',
#             'label': 'Purple'
#         },
#         {
#             'color': 'hsl(262, 52%, 47%)',
#             'label': 'Deep Purple'
#         },
#         {
#             'color': 'hsl(231, 48%, 48%)',
#             'label': 'Indigo'
#         },
#         {
#             'color': 'hsl(207, 90%, 54%)',
#             'label': 'Blue'
#         },
# ]

# TINYMCE_DEFAULT_CONFIG = {
#     'height': 360,
#     'width': 'auto',
#     'menubar': True,
#     'toolbar': 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | outdent indent | link image | code',
#     'plugins': [
#         'advlist autolink link image lists charmap print preview hr anchor pagebreak',
#         'searchreplace wordcount visualblocks visualchars fullscreen code',
#         'insertdatetime media nonbreaking save table contextmenu directionality',
#         'emoticons template paste textcolor colorpicker textpattern'
#     ],
#     'content_css': [
#         '//www.tiny.cloud/css/codepen.min.css'
#     ],
#     'browser_spellcheck': True,
#     'link_context_toolbar': True,
#     'automatic_uploads': True,
#     'advcode_inline': True,
#     'file_picker_types': 'image',
#     'images_upload_url': 'images/',
# }

# CKEDITOR_5_CONFIGS = {
#     'default': {
#         'toolbar': ['heading', '|', 'bold', 'italic', 'link',
#                     'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],

#     },
    
#     'extends': {
#         'blockToolbar': [
#             'paragraph', 'heading1', 'heading2', 'heading3',
#             '|',
#             'bulletedList', 'numberedList',
#             '|',
#             'blockQuote',
#         ],
#         'toolbar': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
#         'code','subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
#                     'bulletedList', 'numberedList', 'todoList', '|',  'blockQuote', 'imageUpload', '|',
#                     'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
#                     'insertTable',],
#         'image': {
#             'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
#                         'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
#             'styles': [
#                 'full',
#                 'side',
#                 'alignLeft',
#                 'alignRight',
#                 'alignCenter',
#             ]

#         },
#         'table': {
#             'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
#             'tableProperties', 'tableCellProperties' ],
#             'tableProperties': {
#                 'borderColors': customColorPalette,
#                 'backgroundColors': customColorPalette
#             },
#             'tableCellProperties': {
#                 'borderColors': customColorPalette,
#                 'backgroundColors': customColorPalette
#             }
#         },
#         'heading' : {
#             'options': [
#                 { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
#                 { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
#                 { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
#                 { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' }
#             ]
#         },
#     },
    
#     'list': {
#         'properties': {
#             'styles': 'true',
#             'startIndex': 'true',
#             'reversed': 'true',
#         }
#     }
# }






MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ukniga_NEW.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'post_page.context_processors.menu_and_breadcrumbs',
                'post_page.context_processors.latest_post_processor',
            ],
            # 'libraries': {
            #     'swiper_slider': 'post_page.templatetags.swiper_slider',
            # }
        }, 
    },
]

WSGI_APPLICATION = 'ukniga_NEW.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": "uknigadb",
#         "USER": "postgres",
#         "PASSWORD": "7887",
#         "HOST": "localhost",
#         "PORT": "",
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'unkniga11',        # Имя вашей базы данных
        'USER': 'root',  # Ваш пользователь MySQL
        'PASSWORD': 'Zzz112233', # Ваш пароль MySQL
        'HOST': 'localhost',         # Хост базы данных (обычно 'localhost')
        'PORT': '3306',              # Порт базы данных MySQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_DIR = os.path.join(BASE_DIR, 'static') #присоединяем папку статик
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [STATIC_DIR] #директории для статичных файлов

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# LOGIN_REDIRECT_URL = '/cabinet/'  # Здесь указывается URL для перенаправления
# LOGOUT_REDIRECT_URL = '/'
# AUTHENTICATION_BACKENDS = [
#     'django.contrib.auth.backends.ModelBackend',
#     # Дополнительные бэкенды, если нужно
# ]









AUTHENTICATION_BACKENDS = (
    # ...
    'allauth.account.auth_backends.AuthenticationBackend',
)

AUTH_USER_MODEL = 'auth.User'  # Используйте кастомную модель пользователя, если у вас есть

MIDDLEWARE = [
    # ...
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

]

ACCOUNT_FORMS = {
    'signup': 'userprofile.forms.CustomSignupForm',
}

# Настройки для Django Allauth
ACCOUNT_EMAIL_VERIFICATION = 'MANDATORY'  # Обязательная верификация по email
ACCOUNT_UNIQUE_EMAIL = True  # Требовать уникальный email
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3  # Срок действия ссылки для подтверждения email
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5  # Лимит попыток входа
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300  # Время блокировки после лимита попыток входа (в секундах)


SITE_URL = 'http://127.0.0.1:8000/'